language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run build
  - npm test
after_success:
  - ./scripts/run-on-node-version.sh latest "npm run coverage:coveralls"
  - ./scripts/run-on-node-version.sh latest "codecov"
