language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run build
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - ./scripts/run-on-node-version.sh latest "npm run coverage:coveralls"
  - ./scripts/run-on-node-version.sh latest "codecov"
  - ./scripts/run-on-node-version.sh latest "nyc report --reporter=text-lcov | codacy-coverage"
